#!/usr/bin/env python3
from pathlib import Path
import json,hashlib
D=Path(__file__).resolve().parent
# Finding IDs identify redlines, not independent board defects or passed physical tests.
items=[
(1,'Missing positive +X retention','Four outboard ears, NPTH holes and shoulder/washer capture','CORRECTED_SOURCE_MODEL',['CAD_PATCH_MANIFEST.json','EAR_GEOMETRY.json'],['MECH-02','MECH-03'],'Actual assembly material/load acceptance remains.'),
(2,'Tiny friction-only edge support','Shoulder sleeves carry shear and washers captureZ','CORRECTED_SOURCE_MODEL',['STRUCTURAL_SERVICE_MODEL.json'],['MECH-02','MECH-03'],'Specified sleeves, thickness and material requirements.'),
(3,'Incomplete fit/service envelope','Source-defined73mm-high carrier; body/connector/model gaps enumerated','CONDITIONAL_BOUND',['MECHANICAL_INSTALLATION_RVB22.md','FINAL_COMPONENT_ENVELOPES.json'],['MECH-02','MECH-03','RDA-06'],'Native populated solid and actual vehicle fit not executed; missing body heights explicitly listed.'),
(4,'F101/ESP incompatible whole-board profile','Remove globalF101paste/CPL; adopt laterfactory260C≤3s localoperation','CORRECTED_SOURCE_MODEL',['ASSEMBLY_PROCESS_RVB22.md','CAD_PATCH_MANIFEST.json'],['DFM-08','DFM-09','DRW-05'],'ExactlocalSMDprocess requires assembler acceptance and executedprofile; fuse retained electrically.'),
(5,'Conflicting U201 filled/capped versus tented-via instruction','Supersede tent/no-fill with12filled/capped/planarizedpad41vias','CORRECTED_SOURCE_MODEL',['ASSEMBLY_PROCESS_RVB22.md'],['DRW-04','DFM-09'],'Fabricator construction acceptance and manufacturing export remain.'),
(6,'Wrong or unsupported environmental interpretation','Dashboard65Cair/radiant screen;120F estimate separately identified','CORRECTED_SOURCE_MODEL',['MECHANICAL_INSTALLATION_RVB22.md'],['THERM-02'],'Screen is not measured hotsoak.'),
(7,'Outboard mass and joint strain unmodeled','27beamcases plus CTEjoint-displacement intervals','CONDITIONAL_BOUND',['STRUCTURAL_SERVICE_MODEL.json'],['THERM-05','MECH-03'],'Static/kinematic sensitivity, not plate/modal/joint-fatigue proof.'),
(8,'Retracing polygon spurs in visual/SCAD outline','Generate ordered continuous outline directly fromEdge.Cuts','CORRECTED_SOURCE_MODEL',['rebuild_mechanics.py','CAD_PATCH_MANIFEST.json'],['MECH-02'],'NativeCADexport execution still distinct.'),
(9,'ESP antenna-board overhang omitted from fit','Add6mmESPoverhang and supplierbodymax tofit','CORRECTED_SOURCE_MODEL',['MECHANICAL_INSTALLATION_RVB22.md','FINAL_COMPONENT_ENVELOPES.json'],['MECH-03'],'Actualantenna/cavityclearance required.'),
(10,'Only left carrier attachments provide poor support','Four vehicleM3mounts, rightpairlatermovedbyC03','CORRECTED_SOURCE_MODEL',['GR86_RVB_CARRIER_C03.scad','C03_CARRIER_CHECKS.json'],['MECH-02','MECH-03'],'Allfourmounts required.'),
(11,'Solid carrier blocks heat exchange','Central and wing windows implemented','CORRECTED_SOURCE_MODEL',['GR86_RVB_CARRIER_C03.scad','thermal_network.py'],['THERM-02'],'Windows maynotbe covered byjackets/vehicletrim.'),
(12,'Continuous local worst-load heat safety not established','Executeaverage,position,winganddirectcontactmodels; retainfailures','OPEN_ENGINEERING',['THERMAL_CONTACT_T01_MODEL.json','THERMAL_CONTACT_T01_INVERSE_REQUIREMENTS.json'],['THERM-02','THERM-05'],'Actualnativefilledcopper/interlayer/packageheatmodel plus installationboundarymust satisfyT01requirements; notpassed byuniformsheet sensitivity.'),
(13,'Adiabatic wire heating overstates1800sfaulttemperature','Powerlane finitecoolingODE andinverseh bound','CONDITIONAL_BOUND',['MECHANICAL_INSTALLATION_RVB22.md'],['PWR-02','PWR-06','LAY-06'],'See power/POWER_BOUNDS.json; actualwire/holder/bundlecooling andfuseclearingconditions retained.'),
(14,'Coax shield can create vehicle return path','InsulatingSMAbulkhead andpuckmount source','CORRECTED_SOURCE_MODEL',['SMA_ISOLATOR.scad','PUCK_ISOLATOR.scad','RF_ACCESSORY_ISOLATION_CHECKS.json'],['MECH-03','FMEA-09'],'ExactAdafruitSKU/bodyshapeandinstalledmetalclearanceconditional;Honeywellhousinggroundretained.'),
(15,'Wing area incorrectly implies isothermal copper','AddsourceGNDzones andfiniteCu-neck model','BLOCKED_NATIVE',['THERMAL_WING_GEOMETRY.json','THERMAL_WING_MODEL.json'],['THERM-02','LAY-06'],'Nativefill,connectivityandthermalCu-path extractionrequired.'),
(16,'Wing windows and carrier mounts conflict','C03extendscarrier andmovesrightmountsawayfromwindows','CORRECTED_SOURCE_MODEL',['C03_CARRIER_CHECKS.json'],['MECH-02','MECH-03'],'Hot/wet/notchedmaterialallowables remain engineeringrequirements.'),
(17,'Anchor slots absent from surviving material','Realroundedslots inleft/rightspines','CORRECTED_SOURCE_MODEL',['GR86_RVB_CARRIER_C03_THERMAL.scad'],['RDA-07','MECH-03'],'Exacttieandjacketgrip addressedbyindependentreview; slotpresenceisnotslipproof.'),
(18,'Low pressure and cavity airflow omitted','70/85/101.325kPa convection andinverseopening sensitivity','CONDITIONAL_BOUND',['THERMAL_WING_MODEL.json'],['THERM-02'],'Actualorientation,openingsandlocalair must match declaredinstallation.'),
(19,'Local board curvature and CTE joint motion omitted','Package-chord curvature and mismatchintervals','CONDITIONAL_BOUND',['STRUCTURAL_SERVICE_MODEL.json'],['THERM-05'],'No solderfatiguelife ormaterialcertificate inferred.'),
(20,'PrimaryF1anchors too remote or removed','Leftspine pair(-4,31/37) afterpretensioncorrection','CORRECTED_SOURCE_MODEL',['GR86_RVB_CARRIER_C03_THERMAL.scad'],['RDA-07'],'Selectedinstalledgrip needed;F1harnessgeometryconditional.'),
(21,'Puck mount had posts without capture','Real sidefences andremovableframe','CORRECTED_SOURCE_MODEL',['PUCK_ISOLATOR.scad','RF_ACCESSORY_ISOLATION_CHECKS.json'],['MECH-03'],'ExactpuckSKU/curvedradome/cableexit remainsapplicabilitycondition.'),
(22,'C2064Vpartlife and taller replacement clearance','Adoptpowerlane6.3VXcase and7mmunder-moduledepth','CORRECTED_SOURCE_MODEL',['STRUCTURAL_SERVICE_MODEL.json','FINAL_COMPONENT_ENVELOPES.json'],['MECH-03','THERM-05'],'ActualcapthermalR/RMSconditions ownedby powerlane.'),
(23,'Wing-onlychassis heat path insufficient','ImplementT01insulatedPCB-backstrap10K/Wallocatedpath','CONDITIONAL_BOUND',['THERMAL_CONTACT_T01.scad','THERMAL_CONTACT_T01_SPEC.json','THERMAL_CONTACT_T01_REVIEW.md'],['THERM-02','THERM-05'],'Actualcontactprocess/materialminimumand70Clanding; originalsourceheatgate remainsMECH22-12.'),
(24,'ESP85Crating misread ascase maximum','Correcttoambientimmediatelyoutsidemodule forN8R2','CORRECTED_SOURCE_MODEL',['THERMAL_CONTACT_T01_REVIEW.md'],['THERM-02'],'Localambientlimit remainsapplicable; nofreecase/junction waiver.'),
(25,'BroaderlegacyRFhardwareexclusion blockscontact','Explicitlyrevise onlyT01metalsource underactual15mmguidance','CONDITIONAL_BOUND',['THERMAL_CONTACT_T01_SPEC.json'],['RDA-03','MECH-03'],'RFloading modeledbyRF lane; externalrange/match remainconditional.'),
(26,'Positionmodel coupling/deposition idealizations hidden','ExposeuniformCu/perfectcoupling andallmainheatEPADhypotheses','CORRECTED_SOURCE_MODEL',['THERMAL_CONTACT_T01_INVERSE_REQUIREMENTS.json'],['THERM-02'],'These models do notclose actual-sourceheat safety.'),
(27,'C02rightmountligament only0.65mm','MoveM3holes andextendcarrier; minwindowligament1.3516mm','CORRECTED_SOURCE_MODEL',['C03_CARRIER_CHECKS.json'],['MECH-02','MECH-03'],'Finitefatigue/materialacceptance retained.'),
(28,'Firstenlargedstrip overlapsfinalJ401courtyard','MovecontactY11.8..28.8 andrerunI03courtcheck','CORRECTED_SOURCE_MODEL',['FINAL_COMPONENT_ENVELOPES.json','THERMAL_CONTACT_T01_SPEC.json'],['RDA-06','MECH-03'],'Nativeplug/cable/servicevolume stillrequired; routeUFLtoward−Y.'),
(29,'ExactT18Rhead exceeds2.8mm andhitsfoilzone','Allocatelocal5.2x5.2x3.9mmheads; move rightpairtoY33/39','CORRECTED_SOURCE_MODEL',['GR86_RVB_CARRIER_C03_THERMAL.scad','THERMAL_CONTACT_T01_REVIEW.md'],['RDA-07','MECH-03'],'Independentexacttie/pretension/grip reportgovernsinstalledpullbound.')]
items.append((30,'Left slot webs inadequate for specified retained tension','Local8mmspines; primaryslotsX−4/rightX62.5;2.0mmnominal and1.8mmallocatedworstweb afteractualslotshape correction','CORRECTED_SOURCE_MODEL',['C03_CARRIER_CHECKS.json','GR86_RVB_CARRIER_C03_THERMAL.scad'],['RDA-07','MECH-03'],'Actualhotpretension andlaminateshearallowance remainconditional.'))
items.append((31,'Rectangular strap corners do not fit nominal obround slot','3.9x1.6mm nominal obrounds,fulltolerance/cornerproof andlocalwebreinforcement','CORRECTED_SOURCE_MODEL',['SLOT_SHAPE_CORRECTION_CHECKS.json','GR86_RVB_CARRIER_C03_THERMAL.scad'],['RDA-07','MECH-03'],'Actualjacketfriction,hotretainedtension andmaterialallowables remainconditional.'))
rows=[]
for id,f,c,st,e,crit,cond in items:rows.append({'id':f'MECH22-{id:02}','finding':f,'actual_correction':c,'status':st,'evidencepaths':e,'criteriaIDs':crit,'remainingcondition':cond})
out={'source_final_PCB_sha256':json.loads((D/'FINAL_COMPONENT_ENVELOPES.json').read_text())['source_PCB_sha256'],'scope':'Reconstructed lane; historypreloss hashes are not represented as regeneratedhashes. Originalcriterion physicalacceptance is distinctfromredline source/model disposition.','counts':{s:sum(x['status']==s for x in rows) for s in sorted(set(x['status'] for x in rows))},'redlines':rows}
(D/'REDLINE_DISPOSITIONS.json').write_text(json.dumps(out,indent=2)+'\n')
files=[]
for p in sorted(D.rglob('*')):
 if p.is_file() and '__pycache__' not in p.parts and p.name not in ['FINAL_LANE_MANIFEST.json']:
  files.append({'path':str(p.relative_to(D)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(D/'FINAL_LANE_MANIFEST.json').write_text(json.dumps({'finalPCB_sha256':out['source_final_PCB_sha256'],'files':files,'counts':out['counts']},indent=2)+'\n');print(json.dumps({'redlinecounts':out['counts'],'files':len(files)}))
