"""Bind final MECH22-31 geometry, current T01 rerun, load allowance and installation text."""
from pathlib import Path
import json,hashlib
D=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
write=lambda p,a:p.write_text(json.dumps(a,indent=2)+'\n')
checks=json.loads((D/'SLOT_SHAPE_CORRECTION_CHECKS.json').read_text());m=json.loads((D/'THERMAL_CONTACT_T01_MODEL.json').read_text())
old=json.loads((D/'history_before_slot_shape_fix/THERMAL_CONTACT_T01_MODEL.json').read_text())
m['MECH22_31_current_carrier_binding']={'PCB_sha256':'c2297b8c857d54f525667e9b2dace5f5f538b7c8d651370cc1b40fa2bdfb39c1','carrier_plan_sha256':sha(D/'carrier_slot_geometry.py'),'thermal_SCAD_sha256':sha(D/'GR86_RVB_CARRIER_C03_THERMAL.scad'),'model_script_sha256':sha(D/'thermal_contact_t01_model.py'),'extra_PCB_shadow_mm2':checks['additional_PCB_shadow_mm2'],'max_C206_change_K':max(a['C206_region_max_C']-b['C206_region_max_C'] for a,b in zip(m['cases'],old['cases'])),'scope':'Current carrier shadow is used; historical C02 models remain unchanged. Uniform copper and perfect interlayer coupling remain sensitivity assumptions.'};write(D/'THERMAL_CONTACT_T01_MODEL.json',m)
inv=json.loads((D/'THERMAL_CONTACT_T01_INVERSE_REQUIREMENTS.json').read_text());inv.pop('finalI03_PCB_sha256',None);inv['finalI04_PCB_sha256']=m['MECH22_31_current_carrier_binding']['PCB_sha256'];inv['source_T01_model_sha256']=sha(D/'THERMAL_CONTACT_T01_MODEL.json')
inv['cases']=[]
for a in m['cases']:
 cu=a['effective_continuous_Cu_um'];T=a['C206_region_max_C'];inv['cases'].append({'effective_copper_um':cu,'sheet_conductance_W_K_per_square':300*cu*1e-6+.25*.00144,'C206_region_max_C':T,'remaining_to125C_K':125-T,'remaining_after3K_body_allowance_K':122-T,'maximum_additional_module_path_R_K_W_after3K_body_allowance':max(0,(122-T)/(2.58225*4.815/4.79))})
inv['sampled_requirement']='140um equivalent continuous Cu with perfect layer coupling gives C206119.713C and2.287K after an allocated3K body rise;160um gives116.359C and5.641K. These remain inverse requirements, not native board passes.';write(D/'THERMAL_CONTACT_T01_INVERSE_REQUIREMENTS.json',inv)
c=json.loads((D/'C03_CARRIER_CHECKS.json').read_text());c['new_basic_assembly_bbox_mm']=[108.454766,73,36.50];c['tie_slot_update']={'redline':'MECH22-31','primary_centres_mm':[[-4,31],[-4,37]],'auxiliary_centres_mm':[[62.5,33],[62.5,39]],'nominal_obround_mm':[3.9,1.6],'finished_slot_mm':{'length':[3.8,4.0],'height':[1.5,1.7]},'position_tolerance_mm':.1,'edge_tolerance_mm':.1,'minimum_side_web_mm':1.8,'local_lip_load_allocation_N':30,'carrier_min_thickness_mm':2.85,'nominal_shear_MPa':checks['one_leg30N_nominal_shear_demand_MPa'],'three_times_notch_sensitivity_required_allowable_MPa':checks['three_times_shear_inverse_required_allowable_MPa'],'corner_cases':324,'checks_sha256':sha(D/'SLOT_SHAPE_CORRECTION_CHECKS.json'),'scope':'Actual curved slots checked, with hot retained tension, jacket grip and notched laminate allowable remaining conditional.'};c['scope']='M3 load screen retained; final carrier slot geometry and thermal fitbox supersede historical values. Actual laminate orthotropy, hot/wet strength, preload and fatigue are acceptance conditions. Current T01 uses actual updated shadow; historical C02 thermal models unchanged.';write(D/'C03_CARRIER_CHECKS.json',c)
s=(D/'MECHANICAL_INSTALLATION_RVB22.md').read_text();start=s.index('Primary F1 harness slots');end=s.index('Select **HellermannTyton',start)
s=s[:start]+'''Primary F1 harness slots are centred at **X−4,Y31/37mm** in a local8mm spine (X−8..0,Y28..40). Auxiliary coax slots are **X62.5,Y33/39mm** in the retained right insertX58.5..66.5,Y30..42. The old right slotsY16/22 are removed. Nominal slots are **3.9×1.6mm obrounds**, with finished length3.8–4.0mm and height1.5–1.7mm, no burrs,±0.1mm position and±0.1mm carrier-edge allocation. All324 strap-corner/tolerance cases fit the actual64-facet SCAD slot; the former3×1.5mm obround failed despite having sufficient bounding-box width and height. The2mm nominal webs retain1.8mm after tolerances. At30N on one lip and2.85mm minimum carrier thickness, nominal shear demand is5.848MPa; a3×notch sensitivity requires17.544MPa allowable. This local requirement is distinct from the15MPa gross carrier-screen assumption; actual hot/wet notched laminate acceptance remains necessary.

''' +s[end:]
s=s.replace('X−7..0,Y25..42,Z−16.3..−9mm','X−7.5..−0.5,Y25..42,Z−16.3..−9mm').replace('X−12..−6.8','X−12.5..−7.3').replace('spacing≤7.6mm','spacing≤7.9mm').replace('requireµ≥0.333','requireµ≥0.3445')
s=s.replace('a125g total including thermal hardware produces121.61MPa.','a126g total including thermal hardware and the≤0.086g added slot reinforcement produces122.58MPa. The rounded126g bound supersedes the125g thermal-hardware screen.')
needle='At the right anchors, retain'
pos=s.index(needle);s=s[:pos]+'''The12-circuit F1 mating harness needs **25.4–30mm of relaxed wire from the actual plug wire-exit plane before the first bend, tie or twist**, then the≥30mm minimum bend radius. The first carrier anchor must lie after that free section along the installed wire path. Exact plug-exit coordinates and the external loop remain installation inputs; the basic assembly box and carrier coordinates do not prove this free-exit fit. `F1_FREE_EXIT_ENVELOPE.scad` is a local-coordinate template requiring an installation transform. Keep terminals free to float and unstrained. [Molex430450001-AS,pp2–3](https://www.molex.com/content/dam/molex/molex-dot-com/products/automated/en-us/applicationspecificationspdf/430/43045/430450001-AS-000.pdf)

''' +s[pos:];(D/'MECHANICAL_INSTALLATION_RVB22.md').write_text(s)
p=D/'THERMAL_CONTACT_T01_REVIEW.md';s=p.read_text().replace('bound to final I03','bound to final I04');s=s.replace('The100g base assembly allowance must include the strap or be raised to125g; the125g/20g one-ear flexural screen is121.61MPa versus the declared150MPa material requirement.','The total mass screen is126g including thermal hardware and≤0.086g added slot reinforcement; the126g/20g one-ear flexural demand is122.58MPa versus the declared150MPa material requirement.')
a=s.index('`GR86_RVB_CARRIER_C03_THERMAL.scad` removes');b=s.index('\n\nThe contact does not',a)
s=s[:a]+'''`GR86_RVB_CARRIER_C03_THERMAL.scad` removes auxiliary slotsY16/22. MECH22-31 places primary slotsX−4,Y31/37 and auxiliary slotsX62.5,Y33/39, using3.9×1.6mm nominal obrounds and local8mm reinforcement. The right insert startsY30, retaining1.2mm to the thermal packet'sY28.8 edge. The primary bundle/strap build is≤7.3mm; the right coax build remains≤2.8mm, with localized5.2×5.2×3.9mm heads. Route U.FL away from the strip toward−Y. The actual bundle may not cross the foil, sharp edges or ventilation windows. The unchanged strip source is verified byte-for-byte against its pre-slot-correction version.''' +s[b:]
s=s.replace("The previous models' carrier/shadow geometry remains conservative C02 geometry; no extra C03 carrier area is credited.","The current T01 model uses the final C03 carrier shadow, including4.8814mm² additional PCB shadow from the slot correction. Earlier C02 models remain historical and unchanged.")
a=s.index('At4.815W, the final strip produces');s=s[:a]+'''At4.815W, the final carrier rerun produces C206-region maxima131.595/124.104/119.713/116.359°C for96/120/140/160µm ideal continuous copper. The slot reinforcement raises the evaluated maxima by at most0.0106K; this small change is explicitly included. The first sampled sheet condition leaving an allocated3K for capacitor/body rise remains140µm, equivalent0.04236W/K per square under the stated conductivity model. It leaves2.287K, corresponding to0.881K/W additional local module-path resistance;160µm leaves5.641K or2.173K/W. These inverse budgets expose why unmodeled interlayer/package resistance cannot be ignored. No guaranteed temperature pass is declared.

MECH22-31 adds≤0.086g under3.15mm maximum thickness/2000kg/m³ allocated density. The rounded126g structural screen includes it. Thermal foil geometry, antenna clearance and the basic assembly bounding box are unchanged. Final slot, web, mass and source hashes are recorded in `SLOT_SHAPE_CORRECTION_CHECKS.json`.
''';p.write_text(s)
print('Final slot evidence, installation and current T01 inverse updated')
